# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric (check https://fabricmc.net/develop/ for the newest recommended versions)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.152.1+26.2

# Mod
mod_version=1.0.0
maven_group=dev.morecommands
archives_base_name=more-commands

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
